# Generated by Django 3.0.6 on 2020-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=300)),
                ('prod_category', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
